### ISSUE TITLE
Add New Term - knowledge

### ISSUE THREAD

**Issue by faridseifi** [kgrid/koio#19]
**Preferred term label:**
Knowledge

**Synonyms**
None

**Definition (free text)**
Information or understanding about a subject, obtained through experience or study.

**Parent term**
IAO: Algorithm
http://purl.obolibrary.org/obo/IAO_0000064

**Comment by faridseifi** [comment]
This is a new class. Knowledge can be considered a BFO: Generically Dependent Continuant because it:
- Depends on Bearers: Knowledge exists in the minds of people or in documents, databases, and other media. It does not exist independently of these bearers.
- Can be Replicated: The same piece of knowledge can exist in multiple places simultaneously (e.g., different copies of a book or multiple people knowing the same fact).

By classifying "Knowledge" as a subclass of "Generically Dependent Continuant," we align with the ontological structure that accurately reflects its nature as an information entity that depends on various bearers for its existence.

This term could be added to our ontology using 
```
<!-- Define Knowledge -->
    <owl:Class rdf:about="https://kgrid.org/koio#Knowledge">
        <rdfs:label>Knowledge</rdfs:label>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000030"/> <!-- BFO: Generically Dependent Continuant -->
        <obo:IAO_0000115>Knowledge, def., information or understanding about a subject, obtained through experience or study.</obo:IAO_0000115>
    </owl:Class>
```

**Comment by ajflynn** [comment]
I propose the term "knowledge representation" - as both an abstraction and a concretization, depending on context, instead of the term "knowledge".
