### ISSUE TITLE
exploratory term(s) for tests

### ISSUE THREAD

**Issue by mlconte** [kgrid/koio#37]

**Comment by mlconte** [comment]
- [x] **Identify a candidate term or group of terms for KOIO**
- [x] **Log candidate term or group of terms as an issue in KOIO github repo**  (test, use case, example)
- [x] **Screen existing external ontologies already used for other KOIO terms to see if candidate term or terms exist in one or more of those ontologies that already are used in KOIO -** no candidate terms used by current external ontologies in KOIO


If still looking to 'define' or 'ground' the candidate term or terms after Step 3, search for new external ontologies with the candidate term or terms, or similar terms, that could potentially be added to KOIO 


If no suitable candidate term definitions or groundings can yet be found in other external ontologies, consider the benefits and burdens of defining a new term or terms in KOIO

**Comment by faridseifi** [comment]
define test:
 - definition
- supercalss
define hasTest:
- definition
- domain
- range
-
